-- Run as postgres on RDS instance.

ALTER DATABASE identity OWNER TO identity_app;
ALTER DATABASE flight OWNER TO flight_app;
ALTER DATABASE passenger OWNER TO passenger_app;
ALTER DATABASE booking OWNER TO booking_app;
ALTER DATABASE payment OWNER TO payment_app;

\connect identity
ALTER SCHEMA public OWNER TO identity_app;
GRANT ALL ON SCHEMA public TO identity_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO identity_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO identity_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO identity_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO identity_app;

\connect flight
ALTER SCHEMA public OWNER TO flight_app;
GRANT ALL ON SCHEMA public TO flight_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO flight_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO flight_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO flight_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO flight_app;

\connect passenger
ALTER SCHEMA public OWNER TO passenger_app;
GRANT ALL ON SCHEMA public TO passenger_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO passenger_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO passenger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO passenger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO passenger_app;

\connect booking
ALTER SCHEMA public OWNER TO booking_app;
GRANT ALL ON SCHEMA public TO booking_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO booking_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO booking_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO booking_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO booking_app;

\connect payment
ALTER SCHEMA public OWNER TO payment_app;
GRANT ALL ON SCHEMA public TO payment_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO payment_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO payment_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO payment_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO payment_app;
